            <option  value="Ableton Live"> Ableton live (Ableton) </option>
            <option  value="Acid pro"> Acid pro (Magix Software GmbH) </option>
            <option  value="Acoustica Mixcraft"> Acoustica Mixcraft (Acoustica)</option>
            <option  value="Adobe audition"> Adobe audition (Adobe)</option>
            <option  value="Ardour"> Ardour (Ardour Community)</option>
            <option  value="Audacity"> Audacity (Muse Group) </option>
            <option  value="AudioMulch"> AudioMulch (Sonic Fritter Pty Ltd)</option>
            <option  value="Audiotool"> Audiotool (Audiotool) </option>
            <option  value="Biab"> Biab (Pro max) </option>
            <option  value="Bitwig studio"> Bitwig studio (Bitwig GmbH) </option>
            <option  value="BTV solo"> BTV solo (BKE Technology) </option>
            <option  value="Cakewalk"> Cakewalk (Bandlab) </option>
            <option  value="Caustic"> Caustic (Single cell software)</option>
            <option  value="Cubase"> Cubase (Steinberg) </option>
            <option  value="Digital performer"> Digital performer (Motu)</option>
            <option  value="EnergyXT"> EnergyXT (XT software) </option>
            <option  value="FL studio"> FL studio (Image-Line Software)</option>
            <option  value="Garageband"> Garageband (Apple) </option>
            <option  value="Goldwave"> Goldwave (GoldWave Digital Audio Editor) </option>
            <option  value="Mixbus"> Mixbus (Harrison Audio Consoles)</option>
            <option  value="Hindenburg journalist"> Hindenburg journalist (Hindenburg Systems) </option>
            <option  value="Logic"> Logic pro (Apple)</option>
            <option  value="Luna"> Luna (Universal audio) </option>
            <option  value="Music maker"> Music maker (Magix Software GmbH) </option>
            <option  value="Mainstage"> Mainstage (Apple)</option>
            <option  value="Mulab"> Mulab (mutools) </option>
            <option  value="Non daw studio"> Non daw studio (Tux family) </option>
            <option  value="n-track studio"> n-track studio (n-Track software) </option>
            <option  value="Nuendo"> Nuendo (Steinberg) </option>
            <option  value="OHM studio"> OHM studio (Steam) </option>
            <option  value="Podium"> Podium (Zynewave) </option>
            <option  value="Pro tools"> Pro tools (Avid techology)</option>
            <option  value="Reaper"> Reaper (Cockos incorporated)</option>
            <option  value="Reason"> Reason (Reason studios)</option>
            <option  value="Renoise"> Renoise (Renoise)</option>
            <option  value="RX"> RX (iZotope)</option>
            <option  value="Samplitude"> Samplitude (Magix Software GmbH) </option>
            <option  value="Sequoia"> Sequoia (Magix Software GmbH) </option>
            <option  value="Serato studio"> Serato studio (Serato) </option>
            <option  value="Sonic visualizer"> Sonic visualizer (Queen Mary University) </option>
            <option  value="Soundbooth"> Soundbooth (Adobe) </option>
            <option  value="Soundbridge"> Soundbridge (Soundbridge)</option>
            <option  value="Soundforge"> Soundforge (Magix Software GmbH)</option>
            <option  value="Soundtrap"> Soundtrap (Spotify) </option>
            <option  value="SpectraLayers"> SpectraLayers (Steinberg) </option>
            <option  value="Studio one"> Studio one (PreSonus)</option>
            <option  value="Tenacity"> Tenacity (Tenacity community)</option>
            <option  value="Tracktion"> Tracktion (Tracktion Software Corporation) </option>
            <option  value="Tracktor"> Tracktor (Native instruments) </option>
            <option  value="Waveform"> Waveform (Tracktion Software Corporation) </option>
            <option  value="WaveLab"> WaveLab (Steinberg) </option>
            <option  value="Other"> Other (Not listed here) </option>